### ISSUE TITLE
Cannot find the labels?

### ISSUE THREAD

**Issue by rfitz123** [aitor-garcia-p/hate-speech-dataset#2]
Sorry, I am just not sure where to see the labels for each .txt files? It seems like hate and noHate are mixed in. Is the label in the file name?

**Comment by aitor-garcia-p** [comment]
Hi @rfitz123 

All the annotations, together with other annotation metadata are located in the file [annotations_metadata.csv](https://github.com/aitor-garcia-p/hate-speech-dataset/blob/master/annotations_metadata.csv) in the root of the repository.

It is a comma-separated-values file with an entry per file. The first column of that file is the id of each file (i.e. its name without the extension), and last column is its label.
Fragment of the annotations metadata file (for files 12834217_1.txt and 12834217_2.txt):

file_id 	user_id 	subforum_id 	num_contexts 	label
12834217_1 	572066 	1346 	0 	noHate
12834217_2 	572066 	1346 	0 	noHate

Best regards :-)
